### ISSUE TITLE
Ivy distribution

### ISSUE THREAD

**Issue by Linknpay** [hughjdavey/ngx-stars#8]
```
Processing legacy "View Engine" libraries:
- ngx-stars [es2015/esm2015] (https://github.com/hughjdavey/ngx-stars.git)
Encourage the library authors to publish an Ivy distribution.
```

**Comment by hughjdavey** [comment]
Will look into this

**Comment by hughjdavey** [comment]
Hey is this resolved by 1.6.3?

**Comment by Linknpay** [comment]
will test and let you know. thank you so much!

**Comment by SagarUkrande-GSLab** [comment]
Hey

Getting below error for ngx-stars with 1.5.1 version on angular 12. same issue persist for lasted version which is 1.6.3. Please check

TypeError: Cannot create property 'message' on string '..ngx-stars/fesm2015/ngx-stars.mjs: This application depends upon a library published using Angular version 14.0.0, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
![image](https://user-images.githubusercontent.com/13540211/173896799-c51d2c24-5cbf-46cc-8489-6bc12965b1c8.png)
